# Generated by Django 4.1 on 2022-08-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="نام")),
                (
                    "last_name",
                    models.CharField(max_length=60, verbose_name="نام خانوادگی"),
                ),
                (
                    "father_name",
                    models.CharField(max_length=30, verbose_name="نام پدر"),
                ),
                (
                    "national_code",
                    models.CharField(max_length=10, unique=True, verbose_name="کد ملی"),
                ),
                (
                    "hamgam_or_pressonel_code",
                    models.CharField(max_length=25, verbose_name="کد همگام/پرسنلی"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        default="defualts/user.png", upload_to="account/avatar/"
                    ),
                ),
                (
                    "is_student",
                    models.BooleanField(default=True, verbose_name="دانش آموز"),
                ),
                ("is_teacher", models.BooleanField(default=False, verbose_name="معلم")),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال / غیر فعال"),
                ),
                ("is_staff", models.BooleanField(default=False, verbose_name="کارمند")),
            ],
            options={"abstract": False,},
        ),
    ]
