# Generated by Django 4.1 on 2022-08-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                max_length=60, unique=True, verbose_name="نام خانوادگی"
            ),
        ),
    ]
