# Generated by Django 4.1 on 2022-08-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_user_groups_user_user_permissions"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="is_staff",),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
    ]
