# Generated by Django 4.1 on 2022-08-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_remove_user_is_staff_alter_user_is_superuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="فعال / غیرفعال"),
        ),
    ]
