# Generated by Django 4.1 on 2022-08-29 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_user_is_staff"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "کاربر", "verbose_name_plural": "کاربران"},
        ),
        migrations.AddField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date joined"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="defualts/user.png",
                upload_to="account/avatar/",
                verbose_name="عکس",
            ),
        ),
    ]
