# Generated by Django 3.2.5 on 2022-08-09 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.class', verbose_name='کلاس ها')),
                ('lessons', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='data.lesson', verbose_name='دروس')),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='دانش آموزان')),
            ],
        ),
    ]
