# Generated by Django 4.1 on 2022-08-28 17:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="reportcard", name="lessons",),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quarter1",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(20.0),
                        ],
                        verbose_name="نمره",
                    ),
                ),
                (
                    "quarter2",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(20.0),
                        ],
                        verbose_name="ترم اول",
                    ),
                ),
                (
                    "quarter3",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(20.0),
                        ],
                        verbose_name="میان ترم دوم",
                    ),
                ),
                (
                    "quarter4",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(20.0),
                        ],
                        verbose_name="خرداد",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="data.lesson",
                        verbose_name="نام درس",
                    ),
                ),
                (
                    "rcard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.reportcard",
                        verbose_name="کارنامه",
                    ),
                ),
            ],
            options={"verbose_name": "نمره درس", "verbose_name_plural": "نمرات دروس",},
        ),
    ]
