# Generated by Django 4.1 on 2022-08-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_remove_reportcard_lessons_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportcard",
            name="year",
            field=models.CharField(
                default=-1, max_length=10, verbose_name="سال تحصیلی"
            ),
            preserve_default=False,
        ),
    ]
