# Generated by Django 4.1 on 2022-08-09 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_grade"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="grade",
            options={"verbose_name": "پایه", "verbose_name_plural": "پایه ها"},
        ),
    ]
