# Generated by Django 4.1 on 2022-09-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="banner",
            field=models.ImageField(
                default="media/defaults/news_banner.jpg",
                max_length="200",
                upload_to="media/news/",
            ),
        ),
    ]
